services:
  # Use this to build the app using the stable version of Goku
  builder:
    container_name: goku_builder
    image: iamteejay/goku:app_builder_latest
    volumes:
      - "./:${CONTAINER_APP_ROOT_DIR}"
      # Copy the goku binary, so we can use it to run th generator
      - "${GOKU_BIN_DIR_SRC}/${GOKU_BIN_NAME}:/go-goku/goku/bin/${GOKU_BIN_NAME}"
    working_dir: /go-goku
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - PGPASSWORD=postgres
      - DATABASE_HOST=database
    networks:
      - common-network
    entrypoint: ["tail", "-f", "/dev/null"]

  # Runs the database
  database:
    container_name: goku_database
    image: postgres:alpine3.15
    depends_on:
      - builder
    ports:
      - 5432:5432
    networks:
      - common-network
    working_dir: /go-goku
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - PGPASSWORD=postgres
    command: ["postgres"]
  
  # Runs the backend
  backend:
    container_name: goku_backend
    image: golang:1.18.3
    depends_on:
      - builder
      - database
    ports:
      - 8080:8080 # Rest API
      - 8081:8081 # Gateway (Graphql)
    networks:
      - common-network
    volumes:
      - "./:${CONTAINER_APP_ROOT_DIR}"
      # Copy workspace dev stuff. Only needed during Goku development. Comment these out for app development!
      - "${GOGOKU_ROOT_DIR}/Makefile:/go-goku/Makefile"
      - "${GOGOKU_ROOT_DIR}/goku-util:/go-goku/goku-util"
      - "${GOGOKU_ROOT_DIR}/gopi:/go-goku/gopi"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - PGPASSWORD=postgres
      - DATABASE_HOST=database
    working_dir: /go-goku
    command: ["make", "-C", "${CONTAINER_APP_ROOT_DIR}", "-f", "container.Makefile", "backend-dev"] # For Goku development
    # command: ["make", "-C", "${CONTAINER_APP_ROOT_DIR}", "-f", "container.Makefile", "backend"] # For pure app development

  # Runs the frontend app
  frontend:
    container_name: goku_frontend
    # image: iamteejay/goku:app_frontend_latest
    build:
      context: frontend
      dockerfile: Dockerfile.frontend
    depends_on:
      - builder
      - database
      - backend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_HOST=localhost
      - REACT_APP_BACKEND_PORT=8080
      - HOST=0.0.0.0 # Post for the frontend to run
    networks:
      - common-network
    volumes:
      - "./:${CONTAINER_APP_ROOT_DIR}"
    working_dir: /go-goku
    command: [sh, -c, "make -C ${CONTAINER_APP_ROOT_DIR} -f container.Makefile frontend-admin-run"]

networks:
  common-network: