services:
  # Use this to build the app using the stable version of Goku
  builder:
    # environment:
      # - SSH_AUTH_SOCK=/ssh-agent
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        - GIT_CLONE_GOKU=1
        - GOKU_BIN_DIR=/go-goku/bin
      secrets:
        - ssh_private_key
    volumes:
      - "./:/go-goku/app"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - PGPASSWORD=postgres
      - DATABASE_HOST=database
      - GOKU_BIN_DIR=/go-goku/bin
    networks:
      - common-network

  # Runs the database
  database:
    image: postgres:alpine3.15
    depends_on:
      - builder
    ports:
      - 5432:5432
    networks:
      - common-network
      - goku-network-database-dev
    volumes:
      - "./:/go-goku/app"
    working_dir: "/go-goku/app"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - PGPASSWORD=postgres
    command: ["postgres"]
  
  # Runs the backend
  backend:
    image: golang:1.18.3
    depends_on:
      - builder
      - database
    ports:
      - 8080:8080 # Rest API
      - 8081:8081 # Gateway (Graphql)
    networks:
      - common-network
    volumes:
      - "./:/go-goku/app"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - PGPASSWORD=postgres
      - DATABASE_HOST=database
      - GOKU_BIN_DIR=/go-goku/bin
    working_dir: /go-goku/app
    command: ["make", "run-backend"]

  # Runs the frontend app
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.frontend
    depends_on:
      - builder
      - backend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_HOST=localhost
      - REACT_APP_BACKEND_PORT=8080
      - HOST=0.0.0.0 # Post for the frontend to run
    networks:
      - common-network
    volumes:
      - "./:/go-goku/app"
    working_dir: /go-goku/app
    command: ["yarn", "workspace", "admin", "start"]
    # entrypoint: ["tail", "-f", "/dev/null"]

networks:
  common-network:
  goku-network-database-dev:
      name: goku-network-database-dev

secrets:
  ssh_private_key:
    file: ~/.ssh/id_ed25519
